routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'nocache'], function () {
    Auth::routes(['register' => false]);
});

Route::get('/', function () {
    return redirect(route('login'));
});
Route::get('abort-authentication', '\App\Http\Controllers\Auth\LoginController@abortAuthentication');

// for registration
Route::post('/2fa', function () {
    return redirect(route('home'));
})->name('2fa')->middleware('2fa');

Route::get('/complete-registration', 'Auth\RegisterController@completeRegistration');
Route::post('/user/password/reset', 'Auth\RegisterController@forgotPassword')->name('register.forgotPassword');
Route::get('/check_password_reset_token/{id}', 'Auth\RegisterController@checkToken')->name('register.checkToken');
Route::post('/reset_user_password', 'Auth\RegisterController@makePassword')->name('register.makePassword');
Route::get('/reset_user_2fa', 'Auth\RegisterController@register')->name('register.register_2fa');

Route::group(['middleware' => ['auth', '2fa']], function () {
    // Roles and users
    Route::resource('roles', 'RolesController');

    Route::resource('users', 'UsersController');
    Route::prefix('user')->group(function () {
        Route::get('profile', 'UsersController@profile')->name('user.profile');
        Route::get('password', 'UsersController@showChangePassword');
        Route::post('password', 'UsersController@changePassword')->name('user.changePassword');
        Route::post('reset/{id}', 'UsersController@resetPassword')->name('users.resetPassword');
    });

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('roles/removeRole/{id}', 'RolesController@removeRolePermissionShow');
    Route::post('role/removePerm/{id}', 'RolesController@removeRolePermission');

    //for patient
    Route::get('/patients/duplicates', 'PatientsController@findDuplicates')->name('patients.findDuplicates');
    Route::post('/patients/duplicates/search', 'PatientsController@searchDuplicates')->name('patients.searchDuplicates');
    Route::post('/patients/duplicates/delete', 'PatientsController@destroy')->name('patients.destroy');
    Route::get('/patients/compare/{id1}/{id2}', 'PatientsController@compare')->name('patients.compare');
    Route::get('/patients/merge/{id1}/{id2}', 'PatientsController@mergeShow')->name('patients.mergeShow');
    Route::post('/patients/merge', 'PatientsController@merge')->name('patients.merge');
    Route::post('/patients/getPatients', 'PatientsController@getPatients')->name('patients.getPatients');
    Route::post('/patients/{id}/drop', 'PatientsController@dropForAnalysis')->name('patients.drop');
    Route::post('/patients/bulk-drop', 'PatientsController@bulkDropForAnalysis')->name('patients.bulkDrop');
    Route::post('/patients', 'PatientsController@index')->name('patients.filter');
    Route::resource('patients', 'PatientsController')->only([
        'index', 'show', 'destroy',
    ]);

    //for medical case
    Route::get('/medical-cases/duplicates', 'MedicalCasesController@findDuplicates')->name('medical-cases.findDuplicates');
    Route::get('/medical-cases/duplicate2', 'MedicalCasesController@findDuplicates2')->name('medical-cases.findDuplicates2');
    Route::get('/medical-cases/compare/{id1}/{id2}', 'MedicalCasesController@compare')->name('medical-cases.compare');
    Route::get('/medical-cases/{medicalCaseId}/question/{questionId}', 'MedicalCasesController@medicalCaseQuestion')->name('medical-cases.medicalCaseQuestion');
    Route::post('/medical-cases/{medicalCaseId}/question/{questionId}/update', 'MedicalCaseAnswersController@update')->name('medical-cases.update');
    Route::get('/medical-cases/changes/{id}', 'MedicalCasesController@showCaseChanges')->name('medical-cases.showCaseChanges');
    Route::post('/medical-cases/duplicates/search', 'MedicalCasesController@searchDuplicates')->name('medical-cases.searchDuplicates');
    Route::post('/medicalCases/duplicates/delete', 'MedicalCasesController@destroy')->name('medical-cases.destroy');
    Route::post('/medicalCases/remove_follow_up', 'MedicalCasesController@deduplicate_redcap')->name('medical-cases.deduplicate_redcap');
    Route::post('/medical-cases/getMedicalCases', 'MedicalCasesController@getMedicalCases')->name('medical-cases.getMedicalCases');
    Route::post('/medical-cases/{id}/drop', 'MedicalCasesController@dropForAnalysis')->name('medical-cases.drop');
    Route::post('/medical-cases/bulk-drop', 'MedicalCasesController@bulkDropForAnalysis')->name('medical-cases.bulkDrop');
    Route::post('/medical-cases', 'MedicalCasesController@index')->name('medical-cases.filter');
    Route::resource('medical-cases', 'MedicalCasesController')->only([
        'index', 'show', 'destroy',
    ]);

    //for followup
    Route::get('/followUp/delayed', 'MedicalCasesController@followUpDelayed');
    Route::get('/followUp', 'MedicalCasesController@showFacilities');
    Route::get('/followUp/show/{id}', 'MedicalCasesController@showFacility')->name('MedicalCasesController.showFacility');

    //for questions
    Route::resource('questions', 'QuestionsController')->only([
        'index', 'show',
    ]);

    //for facilities
    Route::resource('facilities', 'FacilitiesController')->only([
        'index',
    ]);

    //for logs
    Route::resource('logs', 'LogsController')->only([
        'index',
    ]);
    Route::post('/logs/{log_file_name}', 'LogsController@downloadLog')->name('log-downloader');
    Route::get('/logs/{log_file_name}', 'LogsController@show');

    //for failed json folder
    Route::resource('failed', 'FailedJsonController')->only([
        'index',
    ]);

    //for audit trail
    Route::resource('audits', 'AuditsController')->only([
        'index', 'show',
    ]);

    //for health facilities
    Route::group(['middleware' => ['permission:Manage_Health_Facilities']], function () {
        Route::resource('health-facilities', 'HealthFacilityController')->only([
            'index', 'store', 'update', 'destroy',
        ]);
        //Medical staff Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-medical-staff', 'HealthFacilityController@manageMedicalStaff');
        Route::post('health-facilities/{health_facility}/assign-medical-staff/{medical_staff}', 'HealthFacilityController@assignMedicalStaff');
        Route::post('health-facilities/{health_facility}/unassign-medical-staff/{medical_staff}', 'HealthFacilityController@unassignMedicalStaff');
        //Device Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-devices', 'HealthFacilityController@manageDevices');
        Route::post('health-facilities/{health_facility}/assign-device/{device}', 'HealthFacilityController@assignDevice');
        Route::post('health-facilities/{health_facility}/unassign-device/{device}', 'HealthFacilityController@unassignDevice');
        //Algorithms Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-algorithms', 'HealthFacilityController@manageAlgorithms');
        Route::get('health-facilities/{health_facility}/accesses', 'HealthFacilityController@accesses');
        Route::get('health-facilities/versions/{algorithm_id}', 'HealthFacilityController@versions');
        Route::post('health-facilities/{health_facility}/assign-version/{algorithm_id}/{version_id}', 'HealthFacilityController@assignVersion');
        // Sticker Management in the contet of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-stickers', 'HealthFacilityController@manageStickers');
        Route::get('generate-stickers', 'StickerController@downloadView');
        // Drop for Analysis management
        Route::get('health-facilities/{health_facility}/manage-drop', 'HealthFacilityController@manageDrop');
        Route::post('health-facilities/{id}/drop', 'HealthFacilityController@dropForAnalysis');
        // Token management
        Route::get('devices/{devices}/manage-tokens', 'DeviceController@manageTokens');
        Route::get('devices/{devices}/revoke-tokens', 'DeviceController@revokeTokens');
    });

    // Devices
    Route::resource('devices', 'DeviceController')->only([
        'store', 'update', 'destroy',
    ]);

    Route::get('devices/hubmanager', 'DeviceController@hubManager')->name('devices.hubmanager');
    Route::get('devices/{type?}', 'DeviceController@index')->name('devices.index');

    Route::prefix('device')->group(function () {
        Route::get('{device}', 'DeviceController@showAutoDiagnostics')->name('diagnostic.show');
        Route::get('{device}/{file}', 'DeviceController@getRecentErrors')->name('recent_errors.show');
    });

    // Medical Staff
    Route::resource('medical-staff', 'MedicalStaffController');
    Route::post('medical-staff/export', 'MedicalStaffController@export');


    // Drugs
    Route::get('/drugs', 'DrugController@index')->name('drugs.index');
    Route::get('/drugs/getDrugs', 'DrugController@getDrugs')->name('drugs.getDrugs');

    // Diagnoses
    Route::get('/diagnoses', 'DiagnosisController@index')->name('diagnoses.index');
    Route::get('/diagnoses/getDiagnoses', 'DiagnosisController@getDiagnoses')->name('diagnoses.getDiagnoses');

    //for downloading exports
    Route::get('/export/patients', 'ExportsController@patients')->name('exports.patients');
    Route::get('/export/medicalcases', 'ExportsController@cases')->name('exports.cases');
    Route::get('/export/answers', 'ExportsController@answers')->name('exports.answers');

resources/views/medicalCases/compare.blade.php
@extends('adminlte::page')
<script src="{{ mix('js/highlight.js') }}" defer></script>
<link href="{{ asset('css/custom.css') }}" rel="stylesheet">

@section('content')
    <div class="compare_container">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header"><a href="{{ route('medical-cases.findDuplicates') }}"
                                class="btn btn-outline-dark">Back</a></div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <div class="row sticky-top">
                                <div class="col-md-6">
                                    @include(
                                        'medicalCases.includes.firstMedicalCase'
                                    )
                                </div>
                                <div class="col-md-6">
                                    @include(
                                        'medicalCases.includes.secondMedicalCase'
                                    )
                                </div>
                            </div>
                            @if ($medical_case_info)
                                @foreach ($medical_case_info as $case)
                                    <div class="card compare">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="question card">
                                                    <span class="my-2"><strong>Question</strong>: {{ $case['question_label'] }}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="answer card">
                                                    <span class="my-2"><strong>Answer</strong>: {{ $case['first_answer'] }}</span>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="answer card">
                                                    <span class="my-2"><strong>Answer</strong>: {{ $case['second_answer'] }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            @else
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="question card">
                                            <span class="my-2"><strong>Question</strong>: There is no information to Compare</span>
                                        </div>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/medicalCases/compareModal.blade.php
<link href="{{ mix('css/jquery.dataTables.min.css') }}" rel="stylesheet">

<div class="modal" tabindex="-1" id="modalCheckBox" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Compare Patients</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="display1">Compare between Two Patients</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="modalCheckBoxMedical" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Compare Medical Cases</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="display">Compare between Two Medical Cases</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" id="modalCheckBoxMerge" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Compare Patients</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="display">Merge between Two Patients</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

resources/views/medicalCases/followed.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/followup.css') }}" rel="stylesheet">
<script src="{{ mix('js/followup.js') }}" defer></script>
<script src="{{ mix('js/chart.js') }}" defer></script>

@section('content')
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex ">
          <span>
            <h3>Follow-ups In MedAl- Data</h3>
          </span>
        </div>
        <div class="card-body facility">
          @if (session('status'))
          <div class="alert alert-success" role="alert">
            {{ session('status') }}
          </div>
          @endif

          <div class="row">
            <div class="col-md-8">
              <h2 id="facility_title"></h2>
              <canvas id="facility">
              </canvas>
            </div>
            <div class="col-md-4">
              <div class="scrollableDiv">

                @if(count($facilities)>0)
                <ul class="list-group" id="facilities">
                  @foreach($facilities as $facility)
                  <li class="list-group-item" id="{{$facility->group_id}}">{{$facility->name}}</li>
                  @endforeach
                </ul>
                @endif
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div id="sent"><h3></h3></div>
              <div id="not_sent"><h3></h3></div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/medicalCases/index.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@include('medicalCases.compareModal')

@section('content')
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header d-flex ">
            <span>
              <h3>Medical Cases</h3>
            </span>
          </div>
          <div class="card-body">
            @if (session('status'))
              <div class="alert alert-success" role="alert">
                {{ session('status') }}
              </div>
            @endif
            <div class="row">
              <div class="col-md-12">
                <table class="table">
                  <thead>
                    <tr>
                      <th></th>
                      <th scope="col">ID</th>
                      <th scope="col">Case id</th>
                      <th scope="col">Belongs to patient id</th>
                      <th scope="col">Date Created</th>
                      <th scope="col">Facility</th>
                      <th scope="col">App version</th>
                      <th scope="col">Dropped</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @for ($i = 0; $i < 6; $i++)
                      <tr>
                        <td></td>
                        <td scope="row"></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                      </tr>
                    @endfor
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(function() {
      function bulkDrop(dt) {
        var selected = [];

        dt.rows({
          selected: true
        }).data().map((mc) => {
          selected.push(mc.local_medical_case_id);
        })

        $.ajax({
          url: "{{ route('medical-cases.bulkDrop') }}",
          type: 'POST',
          dataType: 'json',
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          data: {
            ids: selected
          },
          success: function(response) {
            Swal.fire({
              title: "Success!",
              text: response.message,
              icon: "success",
              showClass: {
                popup: 'none'
              },
              didClose: function() {
                location.reload();
              }
            })
          },
          error: function(error) {
            var err = JSON.parse(error.responseText);
            Swal.fire({
              icon: 'error',
              title: 'Oops...',
              showClass: {
                popup: 'none'
              },
              text: err.message,
            })
          },
        });
      }

      $(".table").DataTable({
        processing: true,
        serverSide: true,
        "ajax": {
          url: "{{ route('medical-cases.getMedicalCases') }}",
          type: 'POST',
          headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
          },
          data: function(d) {
            d.ids = @json($ids);
          },
        },
        dom: 'Bfrtip',
        select: {
          style: 'os',
          selector: 'td:first-child'
        },
        buttons: [{
            extend: 'selected',
            text: 'Bulk analysis drop',
            action: function(e, dt, button, config) {
              Swal.fire({
                title: 'Are you sure?',
                text: dt.rows({
                  selected: true
                }).data().length + " medical case will be flagged as “Drop for analysis”",
                icon: 'warning',
                confirmButtonColor: '#d33',
                confirmButtonText: 'Confirm'
              }).then((result) => {
                if (result.isConfirmed) {
                  bulkDrop(dt);
                }
              });
            }
          },
          'selectAll',
          'selectNone'
        ],
        columns: [{
            data: null,
            defaultContent: '',
            className: 'select-checkbox',
            orderable: false,
            searchable: false
          },
          {
            data: "id",
          },
          {
            data: "local_medical_case_id",
          },
          {
            data: "local_patient_id",
            name: "patient.local_patient_id",
          },
          {
            data: "consultation_date",
          },
          {
            data: "facility",
            name: "facility.name",
          },
          {
            data: "app_version",
          },
          {
            data: "is_drop",
          },
          {
            data: "show",
            orderable: false,
          },
        ],
      });
    });

    function drop(medical_case_id) {
      Swal.fire({
        title: 'Are you sure?',
        text: "This medical case will be flagged as “Drop for analysis”",
        icon: 'warning',
        confirmButtonColor: '#d33',
        confirmButtonText: 'Confirm'
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            url: "/medical-cases/" + medical_case_id + "/drop",
            type: 'POST',
            dataType: 'json',
            headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(response) {
              Swal.fire({
                title: "Success!",
                text: response.message,
                icon: "success",
                showClass: {
                  popup: 'none'
                },
                didClose: function() {
                  location.reload();
                }
              })
            },
            error: function(error) {
              var err = JSON.parse(error.responseText);
              Swal.fire({
                icon: 'error',
                title: 'Oops...',
                showClass: {
                  popup: 'none'
                },
                text: err.message,
              })
            },
          });
        }
      })
    }
  </script>
@stop

resources/views/medicalCases/question.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/custom.css') }}" rel="stylesheet">

@section('content')
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
      <div class="card-header"><a href="{{route('medical-cases.show',[$medicalCase->id])}}" class="btn btn-outline-dark"> Back</a></div>
        <div class="card-body">
          @if (session('status'))
          <div class="alert alert-success" role="alert">
            {{ session('status') }}
          </div>
          @endif
          <div class="row">
            <div class="col-md-8 offset-md-2">
              @if($medicalCase)
              <div class="mb-2 card-color2" >
                <div class="card-header">
                  <span class="font-weight-bold">Created At: </span>
                  <span>{{$medicalCase->created_at}}</span>
                </div>
                <div class="card-header">
                  <span class="font-weight-bold">Updated At: </span>
                  <span>{{$medicalCase->created_at}}</span> </div>
                  <div class="card-header">
                    <div>
                      <span class="font-weight-bold">Patient Name:</span>
                      <span class="border-bottom">
                        {{$medicalCase->patient->first_name}}
                        {{$medicalCase->patient->last_name}}
                      </span>
                    </div>
                  </div>
                </div>
                <div class="card" style="padding:10px">
                  @if($question)
                  <div class="card">
                    <div class="card-header">
                      <span class="font-weight-bold">Label: </span>
                      <span>{{$question->label}}</span>
                    </div>
                    <div class="card-header">
                      <span class="font-weight-bold">Stage: </span>
                      <span>{{$question->stage}}</span>
                    </div>
                    <div class="card-header">
                      <span class="font-weight-bold">Description: </span>
                      @if($question->description)
                        <span>{{$question->description}}</span>
                      @else
                      <span>No Description was given</span>
                      @endif
                    </div>
                    {{ Form::open(['route' => ['medical-cases.update',$medicalCase,$question->id]]) }}
                    <div class="input-group pl-3">
                      <div class="input-group-prepend">
                        {{Form::label('answer', 'Answer', array('class' => 'input-group-text'))}}
                      </div>
                      @if($answer_type->value =='Date')
                        {{Form::date('answer', \Carbon\Carbon::now(), array('class' => 'form-control'))}}
                      @elseif($answer_type->value =='Float')
                        {{Form::text('answer', '',array('class' => 'form-control'))}}
                      @else
                        {{Form::select('answer', $answers, 'S', array('class' => 'custom-select'))}}
                      @endif
                    </div>
                    <div class="card-header">
                      {{Form::submit('Change Answer', array('class' => 'btn btn-outline-secondary'))}}
                    </div>
                    {{ Form::close() }}
                  </div>
                  @endif
                </div>
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  @stop

resources/views/medicalCases/showCaseChanges.blade.php
@extends('adminlte::page')

@section('content')
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
        <a href="{{route('medical-cases.show',[$medicalCaseId])}}" class="btn btn-outline-dark"> Back</a>
        </div>
        <div class="card-body">
          @if (session('status'))
          <div class="alert alert-success" role="alert">
            {{ session('status') }}
          </div>
          @endif
          <div class="row">
            @include('medicalCases.compareModal')

            <div class="col-md-10 offset-md-1">
              @if($allAudits)
              <table class="table">
                <thead>
                  <th scope="col">SN</th>
                  <th scope="col">User</th>
                  <th scope="col">Question</th>
                  <th scope="col">Old value</th>
                  <th scope="col">New value</th>
                  <th scope="col">Event</th>
                  <th scope="col">Ip address</th>
                  <th scope="col">Created_at</th>
                </thead>
                <tbody>
                  @foreach($allAudits as $audit)
                  <tr>
                    <th scope="row">{{ $loop->index }}</th>
                    <th class="mr-5">{{$audit['user']}}</th>
                    <th>{{$audit['question']}}</th>
                    <th>{{$audit['old_value']}}</th>
                    <th>{{$audit['new_value']}}</th>
                    <th>{{$audit['event']}}</th>
                    <th>{{$audit['ip_address']}}</th>
                    <th>{{$audit['created_at']}}</th>
                  </tr>
                  @endforeach
                </tbody>
              </table>
              @else
              <div id="the_card">
                <h2>There are no changes to this medical Case</h2>
              </div>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/medicalCases/unfollowed.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@section('content')
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex ">
          <span><h3>Delayed Follow-ups</h3></span>
        </div>
        <div class="card-body">
          @if (session('status'))
          <div class="alert alert-success" role="alert">
            {{ session('status') }}
          </div>
          @endif

          <div class="row">
            <div class="col-md-10 offset-md-1">
              @if(count($unfollowed)>0)
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">SN</th>
                    <th scope="col">consultation_ID</th>
                    <th scope="col">patient_id</th>
                    <th scope="col">facility_id</th>
                    <th scope="col">consultation date</th>
                    <th scope="col">village_name</th>
                    {{-- <th scope="col">Actions</th> --}}
                  </tr>
                </thead>
                <tbody>
                  @foreach($unfollowed as $followup)
                  <tr>
                    <th scope="row">{{ $loop->index+1 }}</th>
                    <td>{{$followup->getConsultationId()}}</td>
                    <td>{{$followup->getPatientId()}}</td>
                    <td>{{$followup->getFacilityId()}}</td>
                    <td>{{$followup->getConsultationDate()}}</td>
                    <td>{{$followup->getVillage()}}</td>
                    {{-- <td>Actions</td> --}}
                  </tr>
                  @endforeach
                </tbody>
                @else
                  <span><h3>No Delayed follow ups</h3></span>
                @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop