routes/web.php
    Route::get('roles/removeRole/{id}', 'RolesController@removeRolePermissionShow');
    Route::post('role/removePerm/{id}', 'RolesController@removeRolePermission');

    //for patient
    Route::get('/patients/duplicates', 'PatientsController@findDuplicates')->name('patients.findDuplicates');
    Route::post('/patients/duplicates/search', 'PatientsController@searchDuplicates')->name('patients.searchDuplicates');
    Route::post('/patients/duplicates/delete', 'PatientsController@destroy')->name('patients.destroy');
    Route::get('/patients/compare/{id1}/{id2}', 'PatientsController@compare')->name('patients.compare');
    Route::get('/patients/merge/{id1}/{id2}', 'PatientsController@mergeShow')->name('patients.mergeShow');
    Route::post('/patients/merge', 'PatientsController@merge')->name('patients.merge');
    Route::post('/patients/getPatients', 'PatientsController@getPatients')->name('patients.getPatients');
    Route::post('/patients/{id}/drop', 'PatientsController@dropForAnalysis')->name('patients.drop');
    Route::post('/patients/bulk-drop', 'PatientsController@bulkDropForAnalysis')->name('patients.bulkDrop');
    Route::post('/patients', 'PatientsController@index')->name('patients.filter');
    Route::resource('patients', 'PatientsController')->only([
        'index', 'show', 'destroy',
    ]);

    //for medical case
    Route::get('/medical-cases/duplicates', 'MedicalCasesController@findDuplicates')->name('medical-cases.findDuplicates');
    Route::get('/medical-cases/duplicate2', 'MedicalCasesController@findDuplicates2')->name('medical-cases.findDuplicates2');
    Route::get('/medical-cases/compare/{id1}/{id2}', 'MedicalCasesController@compare')->name('medical-cases.compare');
    Route::get('/medical-cases/{medicalCaseId}/question/{questionId}', 'MedicalCasesController@medicalCaseQuestion')->name('medical-cases.medicalCaseQuestion');
    Route::post('/medical-cases/{medicalCaseId}/question/{questionId}/update', 'MedicalCaseAnswersController@update')->name('medical-cases.update');
    Route::get('/medical-cases/changes/{id}', 'MedicalCasesController@showCaseChanges')->name('medical-cases.showCaseChanges');
    Route::post('/medical-cases/duplicates/search', 'MedicalCasesController@searchDuplicates')->name('medical-cases.searchDuplicates');
    Route::post('/medicalCases/duplicates/delete', 'MedicalCasesController@destroy')->name('medical-cases.destroy');
    Route::post('/medicalCases/remove_follow_up', 'MedicalCasesController@deduplicate_redcap')->name('medical-cases.deduplicate_redcap');
    Route::post('/medical-cases/getMedicalCases', 'MedicalCasesController@getMedicalCases')->name('medical-cases.getMedicalCases');
    Route::post('/medical-cases/{id}/drop', 'MedicalCasesController@dropForAnalysis')->name('medical-cases.drop');
    Route::post('/medical-cases/bulk-drop', 'MedicalCasesController@bulkDropForAnalysis')->name('medical-cases.bulkDrop');
    Route::post('/medical-cases', 'MedicalCasesController@index')->name('medical-cases.filter');
    Route::resource('medical-cases', 'MedicalCasesController')->only([
        'index', 'show', 'destroy',
    ]);

    //for followup
    Route::get('/followUp/delayed', 'MedicalCasesController@followUpDelayed');
    Route::get('/followUp', 'MedicalCasesController@showFacilities');
    Route::get('/followUp/show/{id}', 'MedicalCasesController@showFacility')->name('MedicalCasesController.showFacility');

    //for questions
    Route::resource('questions', 'QuestionsController')->only([
        'index', 'show',
    ]);

    //for facilities
    Route::resource('facilities', 'FacilitiesController')->only([
        'index',
    ]);

    //for logs
    Route::resource('logs', 'LogsController')->only([
        'index',
    ]);
    Route::post('/logs/{log_file_name}', 'LogsController@downloadLog')->name('log-downloader');
    Route::get('/logs/{log_file_name}', 'LogsController@show');

    //for failed json folder
    Route::resource('failed', 'FailedJsonController')->only([
        'index',
    ]);

    //for audit trail
    Route::resource('audits', 'AuditsController')->only([
        'index', 'show',
    ]);

    //for health facilities
    Route::group(['middleware' => ['permission:Manage_Health_Facilities']], function () {
        Route::resource('health-facilities', 'HealthFacilityController')->only([
            'index', 'store', 'update', 'destroy',
        ]);
        //Medical staff Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-medical-staff', 'HealthFacilityController@manageMedicalStaff');
        Route::post('health-facilities/{health_facility}/assign-medical-staff/{medical_staff}', 'HealthFacilityController@assignMedicalStaff');
        Route::post('health-facilities/{health_facility}/unassign-medical-staff/{medical_staff}', 'HealthFacilityController@unassignMedicalStaff');
        //Device Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-devices', 'HealthFacilityController@manageDevices');
        Route::post('health-facilities/{health_facility}/assign-device/{device}', 'HealthFacilityController@assignDevice');
        Route::post('health-facilities/{health_facility}/unassign-device/{device}', 'HealthFacilityController@unassignDevice');
        //Algorithms Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-algorithms', 'HealthFacilityController@manageAlgorithms');
        Route::get('health-facilities/{health_facility}/accesses', 'HealthFacilityController@accesses');
        Route::get('health-facilities/versions/{algorithm_id}', 'HealthFacilityController@versions');
        Route::post('health-facilities/{health_facility}/assign-version/{algorithm_id}/{version_id}', 'HealthFacilityController@assignVersion');
        // Sticker Management in the contet of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-stickers', 'HealthFacilityController@manageStickers');
        Route::get('generate-stickers', 'StickerController@downloadView');
        // Drop for Analysis management
        Route::get('health-facilities/{health_facility}/manage-drop', 'HealthFacilityController@manageDrop');
        Route::post('health-facilities/{id}/drop', 'HealthFacilityController@dropForAnalysis');
        // Token management
        Route::get('devices/{devices}/manage-tokens', 'DeviceController@manageTokens');
        Route::get('devices/{devices}/revoke-tokens', 'DeviceController@revokeTokens');
    });

    // Devices
    Route::resource('devices', 'DeviceController')->only([
        'store', 'update', 'destroy',
    ]);

    Route::get('devices/hubmanager', 'DeviceController@hubManager')->name('devices.hubmanager');
    Route::get('devices/{type?}', 'DeviceController@index')->name('devices.index');

    Route::prefix('device')->group(function () {
        Route::get('{device}', 'DeviceController@showAutoDiagnostics')->name('diagnostic.show');
        Route::get('{device}/{file}', 'DeviceController@getRecentErrors')->name('recent_errors.show');
    });

    // Medical Staff
    Route::resource('medical-staff', 'MedicalStaffController');
    Route::post('medical-staff/export', 'MedicalStaffController@export');


    // Drugs
    Route::get('/drugs', 'DrugController@index')->name('drugs.index');
    Route::get('/drugs/getDrugs', 'DrugController@getDrugs')->name('drugs.getDrugs');

    // Diagnoses
    Route::get('/diagnoses', 'DiagnosisController@index')->name('diagnoses.index');
    Route::get('/diagnoses/getDiagnoses', 'DiagnosisController@getDiagnoses')->name('diagnoses.getDiagnoses');

    //for downloading exports
    Route::get('/export/patients', 'ExportsController@patients')->name('exports.patients');
    Route::get('/export/medicalcases', 'ExportsController@cases')->name('exports.cases');
    Route::get('/export/answers', 'ExportsController@answers')->name('exports.answers');
    Route::get('/export/diagnosis_references', 'ExportsController@diagnosisReferences')->name('exports.diagnosisReferences');
    Route::get('/export/custom_diagnoses', 'ExportsController@customDiagnoses')->name('exports.customDiagnoses');
    Route::get('/export/drug_references', 'ExportsController@drugReferences')->name('exports.drugReferences');
    Route::get('/export/additional_drugs', 'ExportsController@additionalDrugs')->name('exports.additionalDrugs');
    Route::get('/export/management_references', 'ExportsController@managementReferences')->name('exports.managementReferences');
    Route::get('/export/diagnoses', 'ExportsController@diagnoses')->name('exports.diagnoses');
    Route::get('/export/drugs', 'ExportsController@drugs')->name('exports.drugs');
    Route::get('/export/formulations', 'ExportsController@formulations')->name('exports.formulations');
    Route::get('/export/managements', 'ExportsController@managements')->name('exports.managements');
    Route::get('/export/nodes', 'ExportsController@nodes')->name('exports.nodes');
    Route::get('/export/answer_types', 'ExportsController@answer_types')->name('exports.answer_types');
    Route::get('/export/algorithms', 'ExportsController@algorithms')->name('exports.algorithms');
    Route::get('/export/algorithm_versions', 'ExportsController@algorithmVersions')->name('exports.algorithmVersions');
    Route::get('/export/cases_answers', 'ExportsController@casesAnswers2')->name('exports.casesAnswers2');
    Route::get('/export/drug_analysis', 'ExportsController@drugAnalysis')->name('exports.drugAnalysis');
    Route::get('/exports/diagnosis_list', 'ExportsController@diagnosesSummary')->name('exports.diagnosesSummary');
    Route::get('/exports', 'ExportsController@index')->name('exports.selectDate');
    Route::get('/exports/download/{file}', 'ExportsController@DownloadExport')->name('exports.download');
});

// This route needs no Auth For people to see short facility info

app/Device.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Device.
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $name
 * @property string $type
 * @property string|null $mac_address
 * @property string|null $model
 * @property string|null $brand
 * @property string|null $os
 * @property string|null $os_version
 * @property string $redirect
 * @property int $status
 * @property int $user_id
 * @property int|null $health_facility_id
 * @property int|null $oauth_client_id
 * @property string|null $oauth_client_secret
 * @property string|null $last_seen
 * @property-read \App\HealthFacility|null $health_facility
 * @method static \Illuminate\Database\Eloquent\Builder|Device newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Device newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Device query()
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereBrand($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereHealthFacilityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereLastSeen($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereMacAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereModel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereOauthClientId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereOauthClientSecret($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereOs($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereOsVersion($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereRedirect($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Device whereUserId($value)
 * @mixin \Eloquent
 */
class Device extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'type',
        'mac_address',
        'model',
        'brand',
        'os',
        'os_version',
        'status',
        'redirect',
        'oauth_client_id',
    ];

    protected $guarded = [];

    public function health_facility()
    {
        return $this->belongsTo('App\HealthFacility');
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    public function auto_diagnostics()
    {
        return $this->hasMany(AutoDiagnostic::class);
    }
}

app/DeviceType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\DeviceType.
 *
 * @property int $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $type
 * @property string $label
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType query()
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType whereLabel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|DeviceType whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class DeviceType extends Model
{
    //
}

resources/views/devices/create.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@section('content')

@component('layouts.components.create',['url' => 'devices',
                                        'name' => 'Device',
                                        'inputs' => ['Name' => ['keyword' => 'name',
                                                                'type' => 'text'],
                                        ]
                                        ])

@endcomponent


@stop

resources/views/devices/details.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@section('content')


@component('layouts.components.details',[
                                         'instance' => $device,
                                         'name' => 'Device',
                                         'url' => 'devices',
                                         'identifierField' => 'name',
                                         'inputs' => [
                                                      'Name' => 'name',
                                                      'MAC Address' => 'mac_address',
                                                      'Client ID' => 'oauth_client_id',]])
    
@endcomponent


@stop

resources/views/devices/edit.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@section('content')
@component('layouts.components.edit', [
    'instance' => $device,
    'name' => 'Device',
    'url' => 'devices',
    'inputs' => [
        'Name' => [
            'keyword' => 'name',
            'type' => 'text',
        ]
    ]
])

@endcomponent
@endsection

resources/views/devices/hubmanager.blade.php
@extends('adminlte::page')

<link href="{{ asset('css/datatable.css') }}" rel="stylesheet">

@include('medicalCases.compareModal')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <div class="p-2 bd-highlight">
                                <span>
                                    <h3>Hub Manger</h3>
                                </span>
                            </div>
                        </div>

                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-md-10 offset-md-1">
                                    @if (count($devices) > 0)
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th scope="col">SN</th>
                                                    <th scope="col">Hub name</th>
                                                    <th scope="col">Up-to-date</th>
                                                    <th scope="col">Diagnostic recieved</th>
                                                    <th scope="col">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($devices as $device)
                                                    <tr>
                                                        <th scope="row">{{ $device->id }}</th>
                                                        <td>{{ $device->name }}</td>
                                                        @if ($device->is_uptodate)
                                                            <td><i class="fa fa-check" style="color:green !important" aria-hidden="true"></i></td>
                                                        @else
                                                            @if ($device->offset === null)
                                                                <td>No information</td>
                                                            @elseif ($device->offset >= 0)
                                                                <td><i class="fa fa-ban" style="color:red !important" aria-hidden="true"></i> {{$device->offset}} commit{{$device->offset > 1 ? 's' : ''}} behind</td>
                                                            @else
                                                                <td><i class="fa fa-ban" style="color:red !important" aria-hidden="true"></i> More than 30 commits behind</td>
                                                            @endif
                                                        @endif
                                                        @if ($device->auto_diagnostics_count > 0)
                                                            <td><i class="fa fa-check" style="color:green !important" aria-hidden="true"></i></td>
                                                        @else
                                                            <td><i class="fa fa-ban" style="color:red !important" aria-hidden="true"></i></td>
                                                        @endif
                                                        <td>
                                                            @if ($device->offset !== null)
                                                                <a href={{route('diagnostic.show', [$device->id])}} style="cursor: pointer;" class='btn btn-sm btn-outline-dark'>Show</a>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    @else
                                        <span>
                                            <h4>No hub is not up-to-date</h4>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function() {
            $(".table").DataTable({});
        });
    </script>
@stop

resources/views/devices/index.blade.php
@extends('adminlte::page')

 <!-- The contents of the layout/app.bade.php are included so that the view components work correctly -->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <title>
      Devices
    </title>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
</head>


@section('content')

<body>
    <div id="app" class="colorGrey">
    <devices :devices_data="{{$devices}}"
              devices_route="{{route("devices.index")}}"
              health_facilities_route="{{route("health-facilities.index")}}"></devices>
    </div>
</body>

@stop

resources/views/devices/index_old.blade.php
@extends('adminlte::page')


 <!-- The contents of the layout/app.bade.php are included so that the view components work correctly -->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>
      {{-- {{ config('app.name', 'Laravel') }} --}}
      Liwi Main Data
    </title>


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/checkBox.js')}}" defer></script>
    <script src="{{ asset('js/jquery.min.js')}}" defer></script>
    <script src="{{ asset('js/bootstrap.min.js')}}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/resetPassword.css') }}" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->
{{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> --}}
</head>
@section('content')



<body>
    <div id="app" class="colorGrey">
    <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <!-- Here the Passport Vue Components are included -->
                    <passport-clients></passport-clients>
                    <passport-authorized-clients></passport-authorized-clients>
                    <passport-personal-access-tokens></passport-personal-access-tokens>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
</body>

@endsection

resources/views/devices/recent_errors.blade.php
@extends('adminlte::page')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="p-2 d-flex justify-content-between">
                        <div class="p-2 bd-highlight">
                            <span>
                                <h4 lass="card-title">Recent Errors of {{$device->name}}</h4>
                            </span>
                        </div>
                        <div class="ms-auto pt-2 pr-5 bd-highlight">
                            <a onclick="history.back()" class="btn btn-outline-dark" style="cursor: pointer;"> Back</a>
                        </div>
                    </div>
                    @include('partials.recentDiagnosticErrors')
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/devices/showautoDiagnostic.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid">
    @if ($errors->any())
      <div class="col-md-12">
        <div class="alert alert-danger">
          <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
      </div>
    @endif
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="p-2 d-flex justify-content-between">
              <div class="p-2 bd-highlight">
                <span>
                  {{-- <h2>Hub Diagnostics</h2> --}}
                  <h3>Current Hub Status</h3>
                  <h5 class="card-title pt-2">Device {{ $device->name }}</h5>
                  @if (isset($json_diagnostic['last_patient']) && $json_diagnostic['last_patient']['status'])
                    @if ($json_diagnostic['last_patient']['data']['date'])
                      <p class="pt-2 card-text">Last Patient Created:
                        {{ date('Y-m-d H:i:s', strtotime($json_diagnostic['last_patient']['data']['date'])) }}</p>
                    @else
                      <p class="pt-2 card-text">No patient</p>
                    @endif
                  @endif
                </span>
              </div>
              <div class="ms-auto pt-2 pr-5 bd-highlight">
                <a onclick="history.back()" class="btn btn-outline-dark" style="cursor: pointer;"> Back</a>
              </div>
            </div>
            @if ($json_diagnostic)
              @include('partials.diagnosticGit')
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            @include('partials.diagnosticInfo')
          </div>
        </div>
      @else
        @include('partials.noInfo')
        @endif
      </div>
    </div>
  </div>
@stop