routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Svg\Tag\Group;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'nocache'], function () {
    Auth::routes(['register' => false]);
});

Route::get('/', function () {
    return redirect(route('login'));
});
Route::get('abort-authentication', '\App\Http\Controllers\Auth\LoginController@abortAuthentication');

// for registration
Route::post('/2fa', function () {
    return redirect(route('home'));
})->name('2fa')->middleware('2fa');

Route::get('/complete-registration', 'Auth\RegisterController@completeRegistration');
Route::post('/user/password/reset', 'Auth\RegisterController@forgotPassword')->name('register.forgotPassword');
Route::get('/check_password_reset_token/{id}', 'Auth\RegisterController@checkToken')->name('register.checkToken');
Route::post('/reset_user_password', 'Auth\RegisterController@makePassword')->name('register.makePassword');
Route::get('/reset_user_2fa', 'Auth\RegisterController@register')->name('register.register_2fa');

Route::group(['middleware' => ['auth', '2fa']], function () {
    // Roles and users
    Route::resource('roles', 'RolesController');

    Route::resource('users', 'UsersController');
    Route::prefix('user')->group(function () {
        Route::get('profile', 'UsersController@profile')->name('user.profile');
        Route::get('password', 'UsersController@showChangePassword');
        Route::post('password', 'UsersController@changePassword')->name('user.changePassword');
        Route::post('reset/{id}', 'UsersController@resetPassword')->name('users.resetPassword');
    });

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('roles/removeRole/{id}', 'RolesController@removeRolePermissionShow');
    Route::post('role/removePerm/{id}', 'RolesController@removeRolePermission');

    //for patient
    Route::get('/patients/duplicates', 'PatientsController@findDuplicates')->name('patients.findDuplicates');
    Route::post('/patients/duplicates/search', 'PatientsController@searchDuplicates')->name('patients.searchDuplicates');
    Route::post('/patients/duplicates/delete', 'PatientsController@destroy')->name('patients.destroy');
    Route::get('/patients/compare/{id1}/{id2}', 'PatientsController@compare')->name('patients.compare');
    Route::get('/patients/merge/{id1}/{id2}', 'PatientsController@mergeShow')->name('patients.mergeShow');
    Route::post('/patients/merge', 'PatientsController@merge')->name('patients.merge');
    Route::post('/patients/getPatients', 'PatientsController@getPatients')->name('patients.getPatients');
    Route::post('/patients/{id}/drop', 'PatientsController@dropForAnalysis')->name('patients.drop');
    Route::post('/patients/bulk-drop', 'PatientsController@bulkDropForAnalysis')->name('patients.bulkDrop');
    Route::post('/patients', 'PatientsController@index')->name('patients.filter');
    Route::resource('patients', 'PatientsController')->only([
        'index', 'show', 'destroy',
    ]);

    //for medical case
    Route::get('/medical-cases/duplicates', 'MedicalCasesController@findDuplicates')->name('medical-cases.findDuplicates');
    Route::get('/medical-cases/duplicate2', 'MedicalCasesController@findDuplicates2')->name('medical-cases.findDuplicates2');
    Route::get('/medical-cases/compare/{id1}/{id2}', 'MedicalCasesController@compare')->name('medical-cases.compare');
    Route::get('/medical-cases/{medicalCaseId}/question/{questionId}', 'MedicalCasesController@medicalCaseQuestion')->name('medical-cases.medicalCaseQuestion');
    Route::post('/medical-cases/{medicalCaseId}/question/{questionId}/update', 'MedicalCaseAnswersController@update')->name('medical-cases.update');
    Route::get('/medical-cases/changes/{id}', 'MedicalCasesController@showCaseChanges')->name('medical-cases.showCaseChanges');
    Route::post('/medical-cases/duplicates/search', 'MedicalCasesController@searchDuplicates')->name('medical-cases.searchDuplicates');
    Route::post('/medicalCases/duplicates/delete', 'MedicalCasesController@destroy')->name('medical-cases.destroy');
    Route::post('/medicalCases/remove_follow_up', 'MedicalCasesController@deduplicate_redcap')->name('medical-cases.deduplicate_redcap');
    Route::post('/medical-cases/getMedicalCases', 'MedicalCasesController@getMedicalCases')->name('medical-cases.getMedicalCases');
    Route::post('/medical-cases/{id}/drop', 'MedicalCasesController@dropForAnalysis')->name('medical-cases.drop');
    Route::post('/medical-cases/bulk-drop', 'MedicalCasesController@bulkDropForAnalysis')->name('medical-cases.bulkDrop');
    Route::post('/medical-cases', 'MedicalCasesController@index')->name('medical-cases.filter');
    Route::resource('medical-cases', 'MedicalCasesController')->only([
        'index', 'show', 'destroy',
    ]);

    //for followup
    Route::get('/followUp/delayed', 'MedicalCasesController@followUpDelayed');
    Route::get('/followUp', 'MedicalCasesController@showFacilities');
    Route::get('/followUp/show/{id}', 'MedicalCasesController@showFacility')->name('MedicalCasesController.showFacility');

    //for questions
    Route::resource('questions', 'QuestionsController')->only([
        'index', 'show',
    ]);

    //for facilities
    Route::resource('facilities', 'FacilitiesController')->only([
        'index',
    ]);

    //for logs
    Route::resource('logs', 'LogsController')->only([
        'index',
    ]);
    Route::post('/logs/{log_file_name}', 'LogsController@downloadLog')->name('log-downloader');
    Route::get('/logs/{log_file_name}', 'LogsController@show');

    //for failed json folder
    Route::resource('failed', 'FailedJsonController')->only([
        'index',
    ]);

    //for audit trail
    Route::resource('audits', 'AuditsController')->only([
        'index', 'show',
    ]);

    //for health facilities
    Route::group(['middleware' => ['permission:Manage_Health_Facilities']], function () {
        Route::resource('health-facilities', 'HealthFacilityController')->only([
            'index', 'store', 'update', 'destroy',
        ]);
        //Medical staff Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-medical-staff', 'HealthFacilityController@manageMedicalStaff');
        Route::post('health-facilities/{health_facility}/assign-medical-staff/{medical_staff}', 'HealthFacilityController@assignMedicalStaff');
        Route::post('health-facilities/{health_facility}/unassign-medical-staff/{medical_staff}', 'HealthFacilityController@unassignMedicalStaff');
        //Device Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-devices', 'HealthFacilityController@manageDevices');
        Route::post('health-facilities/{health_facility}/assign-device/{device}', 'HealthFacilityController@assignDevice');
        Route::post('health-facilities/{health_facility}/unassign-device/{device}', 'HealthFacilityController@unassignDevice');
        //Algorithms Management in the context of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-algorithms', 'HealthFacilityController@manageAlgorithms');
        Route::get('health-facilities/{health_facility}/accesses', 'HealthFacilityController@accesses');
        Route::get('health-facilities/versions/{algorithm_id}', 'HealthFacilityController@versions');
        Route::post('health-facilities/{health_facility}/assign-version/{algorithm_id}/{version_id}', 'HealthFacilityController@assignVersion');
        // Sticker Management in the contet of Health Facilities
        Route::get('health-facilities/{health_facility}/manage-stickers', 'HealthFacilityController@manageStickers');
        Route::get('generate-stickers', 'StickerController@downloadView');
        // Drop for Analysis management
        Route::get('health-facilities/{health_facility}/manage-drop', 'HealthFacilityController@manageDrop');
        Route::post('health-facilities/{id}/drop', 'HealthFacilityController@dropForAnalysis');
        // Token management
        Route::get('devices/{devices}/manage-tokens', 'DeviceController@manageTokens');
        Route::get('devices/{devices}/revoke-tokens', 'DeviceController@revokeTokens');
    });

    // Devices
    Route::resource('devices', 'DeviceController')->only([
        'store', 'update', 'destroy',
    ]);

    Route::get('devices/hubmanager', 'DeviceController@hubManager')->name('devices.hubmanager');
    Route::get('devices/{type?}', 'DeviceController@index')->name('devices.index');

    Route::prefix('device')->group(function () {
        Route::get('{device}', 'DeviceController@showAutoDiagnostics')->name('diagnostic.show');
        Route::get('{device}/{file}', 'DeviceController@getRecentErrors')->name('recent_errors.show');
    });

    // Medical Staff
    Route::resource('medical-staff', 'MedicalStaffController');
    Route::post('medical-staff/export', 'MedicalStaffController@export');


    // Drugs
    Route::get('/drugs', 'DrugController@index')->name('drugs.index');
    Route::get('/drugs/getDrugs', 'DrugController@getDrugs')->name('drugs.getDrugs');

    // Diagnoses
    Route::get('/diagnoses', 'DiagnosisController@index')->name('diagnoses.index');
    Route::get('/diagnoses/getDiagnoses', 'DiagnosisController@getDiagnoses')->name('diagnoses.getDiagnoses');

    //for downloading exports
    Route::get('/export/patients', 'ExportsController@patients')->name('exports.patients');
    Route::get('/export/medicalcases', 'ExportsController@cases')->name('exports.cases');

resources/views/logs/buttons.blade.php
    <form action="{{ route('logs.index') }}" method="GET" style="display: inline;">
        @csrf
        <button type="submit" class="pull-center btn btn-info" onclick="">
            <i class="fa fa-fw fa-arrow-left"></i> Go back
        </button>
    </form>

    <form class="float-right" action="{{ route('log-downloader', $log_file_name) }}" method="POST"
        style="display: inline;">
        @csrf
        <button type="submit" class="pull-center btn btn-success" onclick="">
            <i class="fa fa-fw fa-download"></i> <br> Download
        </button>
    </form>

resources/views/logs/index.blade.php
@extends('adminlte::page')

@section('content_header')
@stop

@section('content')
<div class="col-md-9 col-lg-12 col-sm-12 pull-left" style="background: white;">
    <div class="panel-body">
        <form action="/users" method="get">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            @if ($message = Session::get('error'))
                <div class="alert alert-danger">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <H3 align="center">
                <b>Logs Information</b>
            </H3>
            {{ csrf_field() }}
        </form>

        <table class="table table-bordered table-striped" >
            <thead>
                <tr>
                    <th>File name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($logs as $log_file_name)
                    <tr>
                        <td>{{$log_file_name}}</td>
                        <td>
                            <form action="{{route('log-downloader', $log_file_name)}}" method="POST">
                                @csrf
                                <button type="submit" class="pull-center btn btn-outline-info btn-sm" onclick="">
                                    <i class="fa fa-fw fa-download"></i> Download
                                </button>
                                <a class="pull-center btn btn-outline-info btn-sm" href="/logs/{{$log_file_name}}" role="button">
                                    <i class="fa fa-fw fa-eye"></i> View
                                </a>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

resources/views/logs/informations.blade.php
@extends('adminlte::page')



@section('content_header')
@stop

@section('content')

@include('partials.errors')
@include('partials.success')


<div class="col-md-9 col-lg-12 col-sm-12 pull-left" style="background: white;">
    <h3 align="center"><b>Showing Log [{{$log_file_name}}]</b></h3>

    @include('logs.buttons')

    <br><br><br>
    @include('logs.labels')
    <br>

    @if(count($logs) > 0 || $search != '')
    <div class="float-left">
        <br>
        @include('logs.search')
    </div>
    <div class="float-right">
        <br>
            @if($search != '' && $log_level != '')
                {{ $logs->appends(['search' => $search, 'log_level' => $log_level])->links() }}
            @elseif($search == '' && $log_level != '')
                {{ $logs->appends(['log_level' => $log_level])->links() }}
            @elseif($search != '' && $log_level == '')
                {{ $logs->appends(['search' => $search])->links() }}
            @else
                {{ $logs->links() }}
            @endif
    </div>

    </div id = "table_data">
        @include('logs.pagination')
    </div>
    @endif
</div>

<script type="text/javascript">
    $(document).ready(function() {
    });
</script>
@stop

resources/views/logs/labels.blade.php
<table style="width:100%;text-align:center;">
        <tbody>
            <tr>
                <td>
                    <a href="{{$log_file_name}}">
                        @if ($log_level == '')
                        <label class="badge" style="background-color:LightGray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-list"></i> ALL</label>
                        <label class="badge" style="background-color:LightGray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ALL'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-list"></i> ALL</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ALL'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=EMERGENCY">
                        @if ($log_level == 'EMERGENCY' || $log_level == '')
                        <label class="badge" style="background-color:#B51B1D; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-bug"></i> EMERGENCY</label>
                        <label class="badge" style="background-color:#B51B1D; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['EMERGENCY'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-bug"></i> EMERGENCY</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['EMERGENCY'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=ALERT">
                        @if ($log_level == 'ALERT' || $log_level == '')
                        <label class="badge" style="background-color:#D32E2C; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-bullhorn"></i> ALERT</label>
                        <label class="badge" style="background-color:#D32E2C; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ALERT'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-bullhorn"></i> ALERT</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ALERT'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=CRITICAL">
                        @if ($log_level == 'CRITICAL' || $log_level == '')
                        <label class="badge" style="background-color:#f44739; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-heartbeat"></i> CRITICAL</label>
                        <label class="badge" style="background-color:#f44739; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['CRITICAL'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-heartbeat"></i> CRITICAL</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['CRITICAL'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=ERROR">
                        @if ($log_level == 'ERROR' || $log_level == '')
                        <label class="badge" style="background-color:#FD5723; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-times-circle"></i> ERROR</label>
                        <label class="badge" style="background-color:#FD5723; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ERROR'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-times-circle"></i> ERROR</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['ERROR'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=WARNING">
                        @if ($log_level == 'WARNING' || $log_level == '')
                        <label class="badge" style="background-color:#FF9003; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-exclamation-triangle"></i> WARNING</label>
                        <label class="badge" style="background-color:#FF9003; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['WARNING'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-exclamation-triangle"></i> WARNING</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['WARNING'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=NOTICE">
                        @if ($log_level == 'NOTICE' || $log_level == '')
                        <label class="badge" style="background-color:#4EAD4F; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-exclamation-circle"></i> NOTICE</label>
                        <label class="badge" style="background-color:#4EAD4F; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['NOTICE'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-exclamation-circle"></i> NOTICE</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['NOTICE'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=INFO">
                        @if ($log_level == 'INFO' || $log_level == '')
                        <label class="badge" style="background-color:#1978D4; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-info-circle"></i> INFO</label>
                        <label class="badge" style="background-color:#1978D4; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['INFO'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-info-circle"></i> INFO</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['INFO'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
                <td>
                    <a href="{{$log_file_name}}?log_level=DEBUG">
                        @if ($log_level == 'DEBUG' || $log_level == '')
                        <label class="badge" style="background-color:#8DCBFC; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-life-ring"></i> DEBUG</label>
                        <label class="badge" style="background-color:#8DCBFC; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['DEBUG'] ?? 0}}</label>
                        @else
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;"><i class="fa fa-fw fa-life-ring"></i> DEBUG</label>
                        <label class="badge" style="background-color:gray; color:white; font-size:90%;cursor:pointer;">{{$log_levels_num['DEBUG'] ?? 0}}</label>
                        @endif
                    </a>
                </td>
            </tr>
        </tbody>
    </table>

resources/views/logs/pagination.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>ENV</th>
                @if ($log_level == '')
                <th>Level</th>
                @endif
                <th>Time</th>
                <th>Header</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
                <tr>
                    <td><label class="badge" style="background-color:#A020F0; color:white; font-size:90%;">{{$log->env}}</label></td>
                    @if ($log_level == '')
                    @if ($log->level == 'EMERGENCY')
                    <td><label class="badge" style="background-color:#B51B1D; color:white; font-size:90%;"><i class="fa fa-fw fa-bug"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'ALERT')
                    <td><label class="badge" style="background-color:#D32E2C; color:white; font-size:90%;"><i class="fa fa-fw fa-bullhorn"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'CRITICAL')
                    <td><label class="badge" style="background-color:#f44739; color:white; font-size:90%;"><i class="fa fa-fw fa-heartbeat"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'ERROR')
                    <td><label class="badge" style="background-color:#FD5723; color:white; font-size:90%;"><i class="fa fa-fw fa-times-circle"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'WARNING')
                    <td><label class="badge" style="background-color:#FF9003; color:white; font-size:90%;"><i class="fa fa-fw fa-exclamation-triangle"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'NOTICE')
                    <td><label class="badge" style="background-color:#4EAD4F; color:white; font-size:90%;"><i class="fa fa-fw fa-exclamation-circle"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'INFO')
                    <td><label class="badge" style="background-color:#1978D4; color:white; font-size:90%;"><i class="fa fa-fw fa-info-circle"></i> {{$log->level}}</label></td>
                    @endif
                    @if ($log->level == 'DEBUG')
                    <td><label class="badge" style="background-color:#8DCBFC; color:white; font-size:90%;"><i class="fa fa-fw fa-life-ring"></i> {{$log->level}}</label></td>
                    @endif
                    @endif
                    <td><label class="badge" style="background-color:gray; color:white; font-size:90%;">{{$log->time}}</label></td>
                    <td style ="word-break:break-all;"><div class="header" style="overflow:hidden;height:30px;cursor:zoom-in;">{!! nl2br(e($log->header)) !!}</div></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <script type="application/javascript">
        $(function() {
            $('.header').click(function() {
                var selection = window.getSelection();
                if(selection.toString().length === 0) {
                    if(this.style.overflow == 'hidden'){
                        $(this).css({
                            'overflow': 'auto',
                            'height': 'auto',
                            'cursor':'zoom-out'
                        });
                    } else {
                        $(this).css({
                            'overflow': 'hidden',
                            'height': '30px',
                            'cursor':'zoom-in'
                        });
                    }
                }
            });
        });
    </script>

resources/views/logs/search.blade.php
@if($log_level != '')
    <form action ={{$log_file_name}} method = "get">
@else
    <form action ={{$log_file_name}} method = "get">
@endif
<div class="input-group mb-3 float-right">
        <div class="input-group-prepend">
                <button type="submit" class="btn btn-danger">Search</button>
        </div>
        <input type="text" class="form-control" name = "search" value = "<?php echo $_GET['search'] ?? ''; ?>">
        @if($log_level != '')
        <input type="hidden" class="form-control" name = "log_level" value = "<?php echo $_GET['log_level'] ?? ''; ?>">
        @endif
    </div>
</form>